/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.9.4.0 (NJsonSchema v10.3.1.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export interface IClient {
    /**
     * @param body (optional) 
     * @return Success
     */
    getProject(body: number | undefined): Promise<ProjectObject[]>;
    /**
     * @param body (optional) 
     * @return Success
     */
    getUserTasks(body: number | undefined): Promise<TaskObject[]>;
    /**
     * @param body (optional) 
     * @return Success
     */
    checkLogin(body: LoginObject | undefined): Promise<UserDto>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createProject(body: ProjectDto | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createColumn(body: CreateColumn | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createTask(body: CreateTask | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createTimeLog(body: CreateTimeLog | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    createUser(body: CreateUser | undefined): Promise<number>;
    /**
     * @param projectId (optional) 
     * @param userId (optional) 
     * @return Success
     */
    setProjectUser(projectId: number | undefined, userId: number | undefined): Promise<number>;
    /**
     * @param taskId (optional) 
     * @param userId (optional) 
     * @return Success
     */
    setTaskUser(taskId: number | undefined, userId: number | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateProject(body: UpdateProject | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateColumn(body: UpdateColumn | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateTask(body: UpdateTask | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateTimeLog(body: UpdateTimeLog | undefined): Promise<number>;
    /**
     * @param body (optional) 
     * @return Success
     */
    updateUser(body: UpdateUser | undefined): Promise<number>;
}

export class Client implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : <any>window;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "https://localhost:44349";
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getProject(body: number | undefined): Promise<ProjectObject[]> {
        let url_ = this.baseUrl + "/Project/GetProject";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetProject(_response);
        });
    }

    protected processGetProject(response: Response): Promise<ProjectObject[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ProjectObject.fromJS(item));
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProjectObject[]>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    getUserTasks(body: number | undefined): Promise<TaskObject[]> {
        let url_ = this.baseUrl + "/Project/GetUserTasks";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetUserTasks(_response);
        });
    }

    protected processGetUserTasks(response: Response): Promise<TaskObject[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TaskObject.fromJS(item));
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TaskObject[]>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    checkLogin(body: LoginObject | undefined): Promise<UserDto> {
        let url_ = this.baseUrl + "/Project/CheckLogin";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheckLogin(_response);
        });
    }

    protected processCheckLogin(response: Response): Promise<UserDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserDto>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createProject(body: ProjectDto | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/CreateProject";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateProject(_response);
        });
    }

    protected processCreateProject(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createColumn(body: CreateColumn | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/CreateColumn";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateColumn(_response);
        });
    }

    protected processCreateColumn(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createTask(body: CreateTask | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/CreateTask";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateTask(_response);
        });
    }

    protected processCreateTask(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createTimeLog(body: CreateTimeLog | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/CreateTimeLog";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateTimeLog(_response);
        });
    }

    protected processCreateTimeLog(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    createUser(body: CreateUser | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/CreateUser";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateUser(_response);
        });
    }

    protected processCreateUser(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param projectId (optional) 
     * @param userId (optional) 
     * @return Success
     */
    setProjectUser(projectId: number | undefined, userId: number | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/SetProjectUser?";
        if (projectId === null)
            throw new Error("The parameter 'projectId' cannot be null.");
        else if (projectId !== undefined)
            url_ += "projectId=" + encodeURIComponent("" + projectId) + "&";
        if (userId === null)
            throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined)
            url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetProjectUser(_response);
        });
    }

    protected processSetProjectUser(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param taskId (optional) 
     * @param userId (optional) 
     * @return Success
     */
    setTaskUser(taskId: number | undefined, userId: number | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/SetTaskUser?";
        if (taskId === null)
            throw new Error("The parameter 'taskId' cannot be null.");
        else if (taskId !== undefined)
            url_ += "taskId=" + encodeURIComponent("" + taskId) + "&";
        if (userId === null)
            throw new Error("The parameter 'userId' cannot be null.");
        else if (userId !== undefined)
            url_ += "userId=" + encodeURIComponent("" + userId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "POST",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetTaskUser(_response);
        });
    }

    protected processSetTaskUser(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateProject(body: UpdateProject | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/UpdateProject";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateProject(_response);
        });
    }

    protected processUpdateProject(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateColumn(body: UpdateColumn | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/UpdateColumn";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateColumn(_response);
        });
    }

    protected processUpdateColumn(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateTask(body: UpdateTask | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/UpdateTask";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateTask(_response);
        });
    }

    protected processUpdateTask(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateTimeLog(body: UpdateTimeLog | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/UpdateTimeLog";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateTimeLog(_response);
        });
    }

    protected processUpdateTimeLog(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    updateUser(body: UpdateUser | undefined): Promise<number> {
        let url_ = this.baseUrl + "/Project/UpdateUser";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateUser(_response);
        });
    }

    protected processUpdateUser(response: Response): Promise<number> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ProblemDetails.fromJS(resultData500);
            return throwException("Server Error", status, _responseText, _headers, result500);
            });
        } else if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number>(<any>null);
    }
}

export class ColumnDto implements IColumnDto {
    columnId?: number;
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    tasks?: TaskDto[] | undefined;

    constructor(data?: IColumnDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.columnId = _data["columnId"];
            this.columnName = _data["columnName"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            if (Array.isArray(_data["tasks"])) {
                this.tasks = [] as any;
                for (let item of _data["tasks"])
                    this.tasks!.push(TaskDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ColumnDto {
        data = typeof data === 'object' ? data : {};
        let result = new ColumnDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["columnId"] = this.columnId;
        data["columnName"] = this.columnName;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        if (Array.isArray(this.tasks)) {
            data["tasks"] = [];
            for (let item of this.tasks)
                data["tasks"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IColumnDto {
    columnId?: number;
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    tasks?: TaskDto[] | undefined;
}

export class ColumnObject implements IColumnObject {
    columnId?: number;
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    tasks?: TaskObject[] | undefined;

    constructor(data?: IColumnObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.columnId = _data["columnId"];
            this.columnName = _data["columnName"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            if (Array.isArray(_data["tasks"])) {
                this.tasks = [] as any;
                for (let item of _data["tasks"])
                    this.tasks!.push(TaskObject.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ColumnObject {
        data = typeof data === 'object' ? data : {};
        let result = new ColumnObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["columnId"] = this.columnId;
        data["columnName"] = this.columnName;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        if (Array.isArray(this.tasks)) {
            data["tasks"] = [];
            for (let item of this.tasks)
                data["tasks"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IColumnObject {
    columnId?: number;
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    tasks?: TaskObject[] | undefined;
}

export class CreateColumn implements ICreateColumn {
    columnName?: string | undefined;
    projectId?: number;
    pointsTotal?: number;
    addedPointsTotal?: number;

    constructor(data?: ICreateColumn) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.columnName = _data["columnName"];
            this.projectId = _data["projectId"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPointsTotal = _data["addedPointsTotal"];
        }
    }

    static fromJS(data: any): CreateColumn {
        data = typeof data === 'object' ? data : {};
        let result = new CreateColumn();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["columnName"] = this.columnName;
        data["projectId"] = this.projectId;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPointsTotal"] = this.addedPointsTotal;
        return data; 
    }
}

export interface ICreateColumn {
    columnName?: string | undefined;
    projectId?: number;
    pointsTotal?: number;
    addedPointsTotal?: number;
}

export class CreateTask implements ICreateTask {
    taskName?: string | undefined;
    comments?: string | undefined;
    pointsTotal?: number;
    addedPointsTotal?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    columnId?: number;

    constructor(data?: ICreateTask) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.taskName = _data["taskName"];
            this.comments = _data["comments"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPointsTotal = _data["addedPointsTotal"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.taskDone = _data["taskDone"];
            this.taskDeleted = _data["taskDeleted"];
            this.taskArchived = _data["taskArchived"];
            this.extensionReason = _data["extensionReason"];
            this.addedReason = _data["addedReason"];
            this.columnId = _data["columnId"];
        }
    }

    static fromJS(data: any): CreateTask {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTask();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taskName"] = this.taskName;
        data["comments"] = this.comments;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPointsTotal"] = this.addedPointsTotal;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["taskDone"] = this.taskDone;
        data["taskDeleted"] = this.taskDeleted;
        data["taskArchived"] = this.taskArchived;
        data["extensionReason"] = this.extensionReason;
        data["addedReason"] = this.addedReason;
        data["columnId"] = this.columnId;
        return data; 
    }
}

export interface ICreateTask {
    taskName?: string | undefined;
    comments?: string | undefined;
    pointsTotal?: number;
    addedPointsTotal?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    columnId?: number;
}

export class CreateTimeLog implements ICreateTimeLog {
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
    userId?: number;
    taskId?: number;

    constructor(data?: ICreateTimeLog) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.totalTime = _data["totalTime"];
            this.billable = _data["billable"];
            this.archived = _data["archived"];
            this.userId = _data["userId"];
            this.taskId = _data["taskId"];
        }
    }

    static fromJS(data: any): CreateTimeLog {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTimeLog();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["totalTime"] = this.totalTime;
        data["billable"] = this.billable;
        data["archived"] = this.archived;
        data["userId"] = this.userId;
        data["taskId"] = this.taskId;
        return data; 
    }
}

export interface ICreateTimeLog {
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
    userId?: number;
    taskId?: number;
}

export class CreateUser implements ICreateUser {
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;

    constructor(data?: ICreateUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.role = _data["role"];
            this.email = _data["email"];
            this.password = _data["password"];
            this.accessToken = _data["accessToken"];
            this.archived = _data["archived"];
        }
    }

    static fromJS(data: any): CreateUser {
        data = typeof data === 'object' ? data : {};
        let result = new CreateUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["role"] = this.role;
        data["email"] = this.email;
        data["password"] = this.password;
        data["accessToken"] = this.accessToken;
        data["archived"] = this.archived;
        return data; 
    }
}

export interface ICreateUser {
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;
}

export class LoginObject implements ILoginObject {
    email?: string | undefined;
    password?: string | undefined;

    constructor(data?: ILoginObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginObject {
        data = typeof data === 'object' ? data : {};
        let result = new LoginObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["password"] = this.password;
        return data; 
    }
}

export interface ILoginObject {
    email?: string | undefined;
    password?: string | undefined;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data; 
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export class ProjectDto implements IProjectDto {
    projectId?: number;
    projectName?: string | undefined;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectCompleated?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;
    users?: UserDto[] | undefined;
    columns?: ColumnDto[] | undefined;

    constructor(data?: IProjectDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectId = _data["projectId"];
            this.projectName = _data["projectName"];
            this.projectStartTime = _data["projectStartTime"] ? new Date(_data["projectStartTime"].toString()) : <any>undefined;
            this.projectEndTime = _data["projectEndTime"] ? new Date(_data["projectEndTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            this.projectCompleated = _data["projectCompleated"];
            this.projectArchived = _data["projectArchived"];
            this.timeIncrement = _data["timeIncrement"];
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(UserDto.fromJS(item));
            }
            if (Array.isArray(_data["columns"])) {
                this.columns = [] as any;
                for (let item of _data["columns"])
                    this.columns!.push(ColumnDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProjectDto {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectId"] = this.projectId;
        data["projectName"] = this.projectName;
        data["projectStartTime"] = this.projectStartTime ? this.projectStartTime.toISOString() : <any>undefined;
        data["projectEndTime"] = this.projectEndTime ? this.projectEndTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        data["projectCompleated"] = this.projectCompleated;
        data["projectArchived"] = this.projectArchived;
        data["timeIncrement"] = this.timeIncrement;
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item.toJSON());
        }
        if (Array.isArray(this.columns)) {
            data["columns"] = [];
            for (let item of this.columns)
                data["columns"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IProjectDto {
    projectId?: number;
    projectName?: string | undefined;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectCompleated?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;
    users?: UserDto[] | undefined;
    columns?: ColumnDto[] | undefined;
}

export class ProjectObject implements IProjectObject {
    projectId?: number;
    projectName?: string | undefined;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectCompleated?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;
    users?: UserObject[] | undefined;
    columns?: ColumnObject[] | undefined;

    constructor(data?: IProjectObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectId = _data["projectId"];
            this.projectName = _data["projectName"];
            this.projectStartTime = _data["projectStartTime"] ? new Date(_data["projectStartTime"].toString()) : <any>undefined;
            this.projectEndTime = _data["projectEndTime"] ? new Date(_data["projectEndTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            this.projectCompleated = _data["projectCompleated"];
            this.projectArchived = _data["projectArchived"];
            this.timeIncrement = _data["timeIncrement"];
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(UserObject.fromJS(item));
            }
            if (Array.isArray(_data["columns"])) {
                this.columns = [] as any;
                for (let item of _data["columns"])
                    this.columns!.push(ColumnObject.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProjectObject {
        data = typeof data === 'object' ? data : {};
        let result = new ProjectObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectId"] = this.projectId;
        data["projectName"] = this.projectName;
        data["projectStartTime"] = this.projectStartTime ? this.projectStartTime.toISOString() : <any>undefined;
        data["projectEndTime"] = this.projectEndTime ? this.projectEndTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        data["projectCompleated"] = this.projectCompleated;
        data["projectArchived"] = this.projectArchived;
        data["timeIncrement"] = this.timeIncrement;
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item.toJSON());
        }
        if (Array.isArray(this.columns)) {
            data["columns"] = [];
            for (let item of this.columns)
                data["columns"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IProjectObject {
    projectId?: number;
    projectName?: string | undefined;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectCompleated?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;
    users?: UserObject[] | undefined;
    columns?: ColumnObject[] | undefined;
}

export class TaskDto implements ITaskDto {
    taskId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    points?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    timelogs?: TimeLogDto[] | undefined;
    users?: UserDto[] | undefined;

    constructor(data?: ITaskDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.taskId = _data["taskId"];
            this.taskName = _data["taskName"];
            this.comments = _data["comments"];
            this.points = _data["points"];
            this.addedPoints = _data["addedPoints"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.taskDone = _data["taskDone"];
            this.taskDeleted = _data["taskDeleted"];
            this.taskArchived = _data["taskArchived"];
            this.extensionReason = _data["extensionReason"];
            this.addedReason = _data["addedReason"];
            if (Array.isArray(_data["timelogs"])) {
                this.timelogs = [] as any;
                for (let item of _data["timelogs"])
                    this.timelogs!.push(TimeLogDto.fromJS(item));
            }
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(UserDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TaskDto {
        data = typeof data === 'object' ? data : {};
        let result = new TaskDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taskId"] = this.taskId;
        data["taskName"] = this.taskName;
        data["comments"] = this.comments;
        data["points"] = this.points;
        data["addedPoints"] = this.addedPoints;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["taskDone"] = this.taskDone;
        data["taskDeleted"] = this.taskDeleted;
        data["taskArchived"] = this.taskArchived;
        data["extensionReason"] = this.extensionReason;
        data["addedReason"] = this.addedReason;
        if (Array.isArray(this.timelogs)) {
            data["timelogs"] = [];
            for (let item of this.timelogs)
                data["timelogs"].push(item.toJSON());
        }
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ITaskDto {
    taskId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    points?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    timelogs?: TimeLogDto[] | undefined;
    users?: UserDto[] | undefined;
}

export class TaskObject implements ITaskObject {
    taskId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    points?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    timelogs?: TimeLogObject[] | undefined;
    users?: UserObject[] | undefined;

    constructor(data?: ITaskObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.taskId = _data["taskId"];
            this.taskName = _data["taskName"];
            this.comments = _data["comments"];
            this.points = _data["points"];
            this.addedPoints = _data["addedPoints"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.taskDone = _data["taskDone"];
            this.taskDeleted = _data["taskDeleted"];
            this.taskArchived = _data["taskArchived"];
            this.extensionReason = _data["extensionReason"];
            this.addedReason = _data["addedReason"];
            if (Array.isArray(_data["timelogs"])) {
                this.timelogs = [] as any;
                for (let item of _data["timelogs"])
                    this.timelogs!.push(TimeLogObject.fromJS(item));
            }
            if (Array.isArray(_data["users"])) {
                this.users = [] as any;
                for (let item of _data["users"])
                    this.users!.push(UserObject.fromJS(item));
            }
        }
    }

    static fromJS(data: any): TaskObject {
        data = typeof data === 'object' ? data : {};
        let result = new TaskObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taskId"] = this.taskId;
        data["taskName"] = this.taskName;
        data["comments"] = this.comments;
        data["points"] = this.points;
        data["addedPoints"] = this.addedPoints;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["taskDone"] = this.taskDone;
        data["taskDeleted"] = this.taskDeleted;
        data["taskArchived"] = this.taskArchived;
        data["extensionReason"] = this.extensionReason;
        data["addedReason"] = this.addedReason;
        if (Array.isArray(this.timelogs)) {
            data["timelogs"] = [];
            for (let item of this.timelogs)
                data["timelogs"].push(item.toJSON());
        }
        if (Array.isArray(this.users)) {
            data["users"] = [];
            for (let item of this.users)
                data["users"].push(item.toJSON());
        }
        return data; 
    }
}

export interface ITaskObject {
    taskId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    points?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
    timelogs?: TimeLogObject[] | undefined;
    users?: UserObject[] | undefined;
}

export class TimeLogDto implements ITimeLogDto {
    timeLogId?: number;
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;

    constructor(data?: ITimeLogDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timeLogId = _data["timeLogId"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.totalTime = _data["totalTime"];
            this.billable = _data["billable"];
            this.archived = _data["archived"];
        }
    }

    static fromJS(data: any): TimeLogDto {
        data = typeof data === 'object' ? data : {};
        let result = new TimeLogDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timeLogId"] = this.timeLogId;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["totalTime"] = this.totalTime;
        data["billable"] = this.billable;
        data["archived"] = this.archived;
        return data; 
    }
}

export interface ITimeLogDto {
    timeLogId?: number;
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
}

export class TimeLogObject implements ITimeLogObject {
    timeLogId?: number;
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;

    constructor(data?: ITimeLogObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.timeLogId = _data["timeLogId"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.totalTime = _data["totalTime"];
            this.billable = _data["billable"];
            this.archived = _data["archived"];
        }
    }

    static fromJS(data: any): TimeLogObject {
        data = typeof data === 'object' ? data : {};
        let result = new TimeLogObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["timeLogId"] = this.timeLogId;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["totalTime"] = this.totalTime;
        data["billable"] = this.billable;
        data["archived"] = this.archived;
        return data; 
    }
}

export interface ITimeLogObject {
    timeLogId?: number;
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
}

export class UpdateColumn implements IUpdateColumn {
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPointsTotal?: number;
    columnId?: number;

    constructor(data?: IUpdateColumn) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.columnName = _data["columnName"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPointsTotal = _data["addedPointsTotal"];
            this.columnId = _data["columnId"];
        }
    }

    static fromJS(data: any): UpdateColumn {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateColumn();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["columnName"] = this.columnName;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPointsTotal"] = this.addedPointsTotal;
        data["columnId"] = this.columnId;
        return data; 
    }
}

export interface IUpdateColumn {
    columnName?: string | undefined;
    pointsTotal?: number;
    addedPointsTotal?: number;
    columnId?: number;
}

export class UpdateProject implements IUpdateProject {
    projectName?: string | undefined;
    projectId?: number;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectComplete?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;

    constructor(data?: IUpdateProject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectName = _data["projectName"];
            this.projectId = _data["projectId"];
            this.projectStartTime = _data["projectStartTime"] ? new Date(_data["projectStartTime"].toString()) : <any>undefined;
            this.projectEndTime = _data["projectEndTime"] ? new Date(_data["projectEndTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            this.projectComplete = _data["projectComplete"];
            this.projectArchived = _data["projectArchived"];
            this.timeIncrement = _data["timeIncrement"];
        }
    }

    static fromJS(data: any): UpdateProject {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateProject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectName"] = this.projectName;
        data["projectId"] = this.projectId;
        data["projectStartTime"] = this.projectStartTime ? this.projectStartTime.toISOString() : <any>undefined;
        data["projectEndTime"] = this.projectEndTime ? this.projectEndTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        data["projectComplete"] = this.projectComplete;
        data["projectArchived"] = this.projectArchived;
        data["timeIncrement"] = this.timeIncrement;
        return data; 
    }
}

export interface IUpdateProject {
    projectName?: string | undefined;
    projectId?: number;
    projectStartTime?: Date;
    projectEndTime?: Date;
    expectedEndTime?: Date;
    pointsTotal?: number;
    addedPoints?: number;
    projectComplete?: string | undefined;
    projectArchived?: string | undefined;
    timeIncrement?: number;
}

export class UpdateTask implements IUpdateTask {
    taskId?: number;
    columnId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;

    constructor(data?: IUpdateTask) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.taskId = _data["taskId"];
            this.columnId = _data["columnId"];
            this.taskName = _data["taskName"];
            this.comments = _data["comments"];
            this.pointsTotal = _data["pointsTotal"];
            this.addedPoints = _data["addedPoints"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.expectedEndTime = _data["expectedEndTime"] ? new Date(_data["expectedEndTime"].toString()) : <any>undefined;
            this.taskDone = _data["taskDone"];
            this.taskDeleted = _data["taskDeleted"];
            this.taskArchived = _data["taskArchived"];
            this.extensionReason = _data["extensionReason"];
            this.addedReason = _data["addedReason"];
        }
    }

    static fromJS(data: any): UpdateTask {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTask();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["taskId"] = this.taskId;
        data["columnId"] = this.columnId;
        data["taskName"] = this.taskName;
        data["comments"] = this.comments;
        data["pointsTotal"] = this.pointsTotal;
        data["addedPoints"] = this.addedPoints;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["expectedEndTime"] = this.expectedEndTime ? this.expectedEndTime.toISOString() : <any>undefined;
        data["taskDone"] = this.taskDone;
        data["taskDeleted"] = this.taskDeleted;
        data["taskArchived"] = this.taskArchived;
        data["extensionReason"] = this.extensionReason;
        data["addedReason"] = this.addedReason;
        return data; 
    }
}

export interface IUpdateTask {
    taskId?: number;
    columnId?: number;
    taskName?: string | undefined;
    comments?: string | undefined;
    pointsTotal?: number;
    addedPoints?: number;
    startTime?: Date;
    endTime?: Date;
    expectedEndTime?: Date;
    taskDone?: string | undefined;
    taskDeleted?: string | undefined;
    taskArchived?: string | undefined;
    extensionReason?: string | undefined;
    addedReason?: string | undefined;
}

export class UpdateTimeLog implements IUpdateTimeLog {
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
    timelogId?: number;

    constructor(data?: IUpdateTimeLog) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.totalTime = _data["totalTime"];
            this.billable = _data["billable"];
            this.archived = _data["archived"];
            this.timelogId = _data["timelogId"];
        }
    }

    static fromJS(data: any): UpdateTimeLog {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTimeLog();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["totalTime"] = this.totalTime;
        data["billable"] = this.billable;
        data["archived"] = this.archived;
        data["timelogId"] = this.timelogId;
        return data; 
    }
}

export interface IUpdateTimeLog {
    startTime?: Date;
    endTime?: Date;
    totalTime?: number;
    billable?: string | undefined;
    archived?: string | undefined;
    timelogId?: number;
}

export class UpdateUser implements IUpdateUser {
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;
    userId?: number;

    constructor(data?: IUpdateUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.role = _data["role"];
            this.email = _data["email"];
            this.password = _data["password"];
            this.accessToken = _data["accessToken"];
            this.archived = _data["archived"];
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): UpdateUser {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["role"] = this.role;
        data["email"] = this.email;
        data["password"] = this.password;
        data["accessToken"] = this.accessToken;
        data["archived"] = this.archived;
        data["userId"] = this.userId;
        return data; 
    }
}

export interface IUpdateUser {
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;
    userId?: number;
}

export class UserDto implements IUserDto {
    userId?: number;
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.userName = _data["userName"];
            this.role = _data["role"];
            this.email = _data["email"];
            this.password = _data["password"];
            this.accessToken = _data["accessToken"];
            this.archived = _data["archived"];
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["userName"] = this.userName;
        data["role"] = this.role;
        data["email"] = this.email;
        data["password"] = this.password;
        data["accessToken"] = this.accessToken;
        data["archived"] = this.archived;
        return data; 
    }
}

export interface IUserDto {
    userId?: number;
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;
}

export class UserObject implements IUserObject {
    userId?: number;
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;

    constructor(data?: IUserObject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.userName = _data["userName"];
            this.role = _data["role"];
            this.email = _data["email"];
            this.password = _data["password"];
            this.accessToken = _data["accessToken"];
            this.archived = _data["archived"];
        }
    }

    static fromJS(data: any): UserObject {
        data = typeof data === 'object' ? data : {};
        let result = new UserObject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["userName"] = this.userName;
        data["role"] = this.role;
        data["email"] = this.email;
        data["password"] = this.password;
        data["accessToken"] = this.accessToken;
        data["archived"] = this.archived;
        return data; 
    }
}

export interface IUserObject {
    userId?: number;
    userName?: string | undefined;
    role?: string | undefined;
    email?: string | undefined;
    password?: string | undefined;
    accessToken?: string | undefined;
    archived?: string | undefined;
}

export class ValidationProblemDetails extends ProblemDetails implements IValidationProblemDetails {
    readonly errors?: { [key: string]: string[]; } | undefined;

    constructor(data?: IValidationProblemDetails) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (_data["errors"]) {
                (<any>this).errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (<any>this).errors![key] = _data["errors"][key] !== undefined ? _data["errors"][key] : [];
                }
            }
        }
    }

    static fromJS(data: any): ValidationProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    data["errors"][key] = this.errors[key];
            }
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IValidationProblemDetails extends IProblemDetails {
    errors?: { [key: string]: string[]; } | undefined;
}

export class SwaggerException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new SwaggerException(message, status, response, headers, result);
}